### ISSUE TITLE
Make this into proper package

### ISSUE THREAD

**Issue by JoschD** [pylhc/omc3#148]
So it can be used as a site-package
- imports absolute, proper order
- PEP8 compliance
- remove context from tests
- check that all tests are still working
- proper setup.py (see other packages, e.g. tfs)

any comments @mihofer @lmalina @Mael-Le-Garrec @awegsche ??

**Comment by Mael-Le-Garrec** [comment]
no comment other than that it's a good thing :tada:
I can help if need

**Comment by Eothred** [comment]
(guess most of you don't know me, I was the fellow who originally started this github team many years ago)

To force a good code style (and avoid some fishy code) I could mention we have lately been using [pre-commit](https://pre-commit.com/) rather successfully. With this you can easily add a pre-commit hook as a developer and it can be used by travis or whichever ci you use. This pre-commit then runs a list of static code check tools you define in a yaml. An example yaml could be

```
repos:
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8
        args: ['--max-line-length=140', '--ignore=E203,E402']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.720'
    hooks:
    -   id: mypy
```

Then you test all staged files with the simple command `pre-commit run` (typically as a hook), or check all files with `pre-commit run --all-files` (typically on travis)
